name: my_toolbox

description: "启动外壳 1. 负责连接框架层和业务层 2. 提供启动方法"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  # 依赖版本管理
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  logger: ^2.6.2
  riverpod_annotation: ^3.0.3
  flutter_riverpod: ^3.0.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  flutter_secure_storage: ^10.0.0
  dio: ^5.9.0
  go_router: ^17.0.1

  core:
    path: packages/core
  auth_biz:
    path: packages/infra/auth-biz
  auth_ui:
    path: packages/infra-ui/auth-ui
  drift: ^2.30.0
  drift_flutter: ^0.2.8
  path: ^1.9.1
  path_provider: ^2.1.5
  sqlite3_flutter_libs: ^0.5.41
  crypto: ^3.0.7
  mmkv: ^2.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  riverpod_generator: ^3.0.3
  #  custom_lint: ^0.8.1
  riverpod_lint: ^3.0.3
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  mockito: ^5.6.1
  http_mock_adapter: ^0.6.1
  drift_dev: ^2.30.0

workspace:
  - packages/core
  - packages/infra-ui/common-ui
  - packages/infra/auth-biz
  - packages/infra/data-biz

dependency_overrides:
  # fixed https://github.com/rrousselGit/riverpod/issues/4428
  analyzer_buffer: 0.1.11

flutter:
  uses-material-design: true
