name: ecs_biz
description: "ecs-实现"
resolution: workspace

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  app_core:
    path: ../../app-core
  framework_api:
    path: ../../framework-api
  common_ui:
    path: ../../infra/common-ui
  json_annotation: ^4.9.0
  material_symbols_icons: any
  flutter_iconpicker: any
  font_awesome_flutter: any
  # db
  drift: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  # riverpod
  riverpod_generator: any
  #  custom_lint: any
  riverpod_lint: any
  # freezed
  freezed: any
  json_serializable: any
  drift_dev: any
