name: auth_biz
description: "用户-实现"
resolution: workspace

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  json_annotation: any

  app_core:
    path: ../../app-core
  auth_api:
    path: ../../api/auth-api
  common_ui:
    path: ../common-ui
  flutter_secure_storage: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  # test
  mockito: any
  http_mock_adapter: any
  # riverpod
  riverpod_generator: any
  #  custom_lint: any
  riverpod_lint: any
  # freezed
  freezed: any
  json_serializable: any



