name: theme_biz
description: "主题-实现"
resolution: workspace

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  json_annotation: any
  app_core:
    path: ../../app-core
  framework_api:
    path: ../../framework-api
  common_ui:
    path: ../common-ui
  dynamic_color: any
  google_fonts: any
  flex_color_scheme: any
  flutter_native_splash: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  # test
  mockito: any
  http_mock_adapter: any
  # riverpod
  riverpod_generator: any
  #  custom_lint: any
  riverpod_lint: any
  # freezed
  freezed: any
  json_serializable: any
  # db
  drift_dev: any


