name: auth_api
description: "鉴权-接口"
resolution: workspace

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  app_core:
    path: ../../app-core
  json_annotation: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  # riverpod
  riverpod_generator: any
  #  custom_lint: any
  riverpod_lint: any
  # freezed
  freezed: any
  json_serializable: any


