name: framework_biz
description: "平台集成实现"
resolution: workspace

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  mmkv: any
  drift: any

  json_annotation: ^4.9.0
  app_core:
    path: ../app-core
  framework_api:
    path: ../framework-api
  auth_biz:
    path: ../infra/auth-biz
  data_biz:
    path: ../infra/data-biz
  sync_biz:
    path: ../infra/sync-biz
  theme_biz:
    path: ../infra/theme-biz
  network_biz:
    path: ../infra/network-biz
  shell_biz:
    path: ../infra/shell-biz

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  # test
  mockito: any
  http_mock_adapter: any
  # riverpod
  riverpod_generator: any
  #  custom_lint: any
  riverpod_lint: any
  # freezed
  freezed: any
  json_serializable: any
  # db
  drift_dev: any

